package UserInterface;

import Classes.Payment;
import Classes.UserRole;
import DAO.PaymentDao;
import DAO.UserDao;
import Processes.PaymentProcess;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class AdminViewPaymentDetailsPanel extends javax.swing.JPanel {
    Payment default_;

    public AdminViewPaymentDetailsPanel() {
        initComponents();
    }

    public void getPaymentId(String id) {
        reset();
        
        PaymentDao paymentDao = new PaymentDao();
        Payment payment = paymentDao.get(id);
        
        PaymentIDTextField.setText(payment.getPaymentId());
        BookingIDTextField.setText(payment.getBookingId());
        StatusTextField.setText(payment.getApproval());
        AdminIDTextField.setText(payment.getAdminId());
        DatetimeTextField.setText(payment.getDatetime());
        PaymentMethodTextField.setText(payment.getMethod());
        AmountTextField.setText(payment.getAmount());

        boolean approve = payment.getApproval().equals("Pending");
        ApproveButton.setEnabled(approve);

        this.default_ = payment;
        
        if (UserDao.loggedIn.getRole().equals(UserRole.CUSTOMER.toString())) {
            ApproveButton.setVisible(false);
        }
        else {
            ApproveButton.setVisible(true);
        }
    }

    public void reset() {
        PaymentIDTextField.setText("");
        BookingIDTextField.setText("");
        StatusTextField.setText("");
        AdminIDTextField.setText("");
        DatetimeTextField.setText("");
        PaymentMethodTextField.setText("");
        AmountTextField.setText("");
        ApproveButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaymentDetailsLabel = new javax.swing.JLabel();
        PaymentIDLabel = new javax.swing.JLabel();
        BookingIDLabel = new javax.swing.JLabel();
        StatusLabel = new javax.swing.JLabel();
        PaymentMethodLabel = new javax.swing.JLabel();
        DatetimeLabel = new javax.swing.JLabel();
        AmountLabel = new javax.swing.JLabel();
        StatusTextField = new javax.swing.JTextField();
        PaymentIDTextField = new javax.swing.JTextField();
        BookingIDTextField = new javax.swing.JTextField();
        PaymentMethodTextField = new javax.swing.JTextField();
        DatetimeTextField = new javax.swing.JTextField();
        AmountTextField = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        ApproveButton = new javax.swing.JButton();
        ApprovedByLabel = new javax.swing.JLabel();
        AdminIDTextField = new javax.swing.JTextField();

        PaymentDetailsLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PaymentDetailsLabel.setText("Payment Details");

        PaymentIDLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PaymentIDLabel.setText("Payment ID");

        BookingIDLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BookingIDLabel.setText("Booking ID");

        StatusLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        StatusLabel.setText("Status");

        PaymentMethodLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PaymentMethodLabel.setText("Payment Method");

        DatetimeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DatetimeLabel.setText("Datetime");

        AmountLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AmountLabel.setText("Amount");

        StatusTextField.setEditable(false);
        StatusTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        PaymentIDTextField.setEditable(false);
        PaymentIDTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        BookingIDTextField.setEditable(false);
        BookingIDTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        PaymentMethodTextField.setEditable(false);
        PaymentMethodTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        DatetimeTextField.setEditable(false);
        DatetimeTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        AmountTextField.setEditable(false);
        AmountTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        BackButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BackButton.setText("Back");
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        ApproveButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ApproveButton.setText("Approve");
        ApproveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ApproveButton.setEnabled(false);
        ApproveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveButtonActionPerformed(evt);
            }
        });

        ApprovedByLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ApprovedByLabel.setText("Approved by");

        AdminIDTextField.setEditable(false);
        AdminIDTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 237, Short.MAX_VALUE)
                .addComponent(ApproveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(PaymentDetailsLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BookingIDLabel)
                                    .addComponent(PaymentIDLabel)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PaymentMethodLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AmountLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PaymentIDTextField)
                            .addComponent(BookingIDTextField)
                            .addComponent(PaymentMethodTextField)
                            .addComponent(AmountTextField))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(StatusLabel)
                                    .addComponent(DatetimeLabel))
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ApprovedByLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AdminIDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(StatusTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DatetimeTextField, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(PaymentDetailsLabel)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PaymentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PaymentIDLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BookingIDLabel)
                            .addComponent(BookingIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StatusLabel)
                            .addComponent(StatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DatetimeLabel)
                            .addComponent(DatetimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaymentMethodLabel)
                    .addComponent(PaymentMethodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApprovedByLabel)
                    .addComponent(AdminIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmountLabel)
                    .addComponent(AmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApproveButton)
                    .addComponent(BackButton))
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BackButtonActionPerformed
        reset();
        Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
        f.bookingDetailPanel.setBookingDetail(default_.getBookingId());
        CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
        cardLayout.show(f.getControlPanel(), "bookingDetailPanel");
    }// GEN-LAST:event_BackButtonActionPerformed

    private void ApproveButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ApproveButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Confirm payment approval?", "Confirmation",
                JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            PaymentProcess pp = new PaymentProcess();
            pp.setPayment(default_.getPaymentId(), default_.getBookingId(), default_.getAdminId(),
                    default_.getDatetime(), default_.getMethod(), default_.getAmount(), default_.getApproval(),
                    default_.getBankId());

            if (pp.approvePayment(UserDao.loggedIn.getIcno())) {
                getPaymentId(default_.getPaymentId());
            } else {
                JOptionPane.showMessageDialog(null, "Failed to confirm payment.");
            }
        }
    }// GEN-LAST:event_ApproveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdminIDTextField;
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JTextField AmountTextField;
    private javax.swing.JButton ApproveButton;
    private javax.swing.JLabel ApprovedByLabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel BookingIDLabel;
    private javax.swing.JTextField BookingIDTextField;
    private javax.swing.JLabel DatetimeLabel;
    private javax.swing.JTextField DatetimeTextField;
    private javax.swing.JLabel PaymentDetailsLabel;
    private javax.swing.JLabel PaymentIDLabel;
    private javax.swing.JTextField PaymentIDTextField;
    private javax.swing.JLabel PaymentMethodLabel;
    private javax.swing.JTextField PaymentMethodTextField;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JTextField StatusTextField;
    // End of variables declaration//GEN-END:variables
}