package UserInterface;

import Classes.User;
import DAO.UserDao;
import Processes.ManageAccProcess;
import Validator.UserValidator;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class AdminViewUserDetailsPanel extends javax.swing.JPanel {
    User default_;

    public AdminViewUserDetailsPanel() {
        initComponents();
    }

    public void getCustId(String id) {
        UserDao userDao = new UserDao();
        User user = userDao.get(id);
        ICNOTextField.setText(user.getIcno());
        UsernameTextField.setText(user.getUsername());
        RoleTextField.setText(user.getRole());
        EmailTextField.setText(user.getEmail());
        PhoneNOTextField.setText(user.getPhone());
        GenderTextField.setText(user.getGender());
        AddressTextArea.setText(user.getAddress1().replace(":", ",") + "\n" + user.getAddress2().replace(":", ",")
                + "\n" + user.getCity() + "\n" + user.getZip() + "\n" + user.getState());
        RegisteredTextField.setText(user.getRegistered());
        CreditBalanceTextField.setText(user.getCreditBalance());

        this.default_ = user;
    }

    public void setEdit() {
        UsernameTextField.setEditable(true);
        EmailTextField.setEditable(true);
        PhoneNOTextField.setEditable(true);
        SaveChangesButton.setEnabled(true);
        ResetButton.setEnabled(true);
        RemoveButton.setEnabled(true);
    }

    public void reset() {
        ICNOTextField.setText("");
        UsernameTextField.setText("");
        RoleTextField.setText("");
        EmailTextField.setText("");
        PhoneNOTextField.setText("");
        GenderTextField.setText("");
        AddressTextArea.setText("");
        RegisteredTextField.setText("");
        CreditBalanceTextField.setText("");
        UsernameTextField.setEditable(false);
        EmailTextField.setEditable(false);
        PhoneNOTextField.setEditable(false);
        SaveChangesButton.setEnabled(false);
        ResetButton.setEnabled(false);
        RemoveButton.setEnabled(false);
        ErrorLabel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ICNOLabel = new javax.swing.JLabel();
        ICNOTextField = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        PhoneNOLabel = new javax.swing.JLabel();
        PhoneNOTextField = new javax.swing.JTextField();
        RoleLabel = new javax.swing.JLabel();
        RoleTextField = new javax.swing.JTextField();
        RegisteredLabel = new javax.swing.JLabel();
        RegisteredTextField = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        GenderTextField = new javax.swing.JTextField();
        CreditBalanceLabel = new javax.swing.JLabel();
        CreditBalanceTextField = new javax.swing.JTextField();
        CustomerDetailsLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        SaveChangesButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        ErrorLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressTextArea = new javax.swing.JTextArea();

        ICNOLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ICNOLabel.setText("NRIC/Passport No.");

        ICNOTextField.setEditable(false);
        ICNOTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UsernameLabel.setText("Username");

        UsernameTextField.setEditable(false);
        UsernameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmailLabel.setText("Email");

        EmailTextField.setEditable(false);
        EmailTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        PhoneNOLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PhoneNOLabel.setText("Phone No.");

        PhoneNOTextField.setEditable(false);
        PhoneNOTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        RoleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RoleLabel.setText("Role");

        RoleTextField.setEditable(false);
        RoleTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        RegisteredLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RegisteredLabel.setText("Registered");

        RegisteredTextField.setEditable(false);
        RegisteredTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        GenderLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GenderLabel.setText("Gender");

        GenderTextField.setEditable(false);
        GenderTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CreditBalanceLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreditBalanceLabel.setText("Credit Balance");

        CreditBalanceTextField.setEditable(false);
        CreditBalanceTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CustomerDetailsLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CustomerDetailsLabel.setText("User Details");

        BackButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BackButton.setText("Back");
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        SaveChangesButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SaveChangesButton.setText("Save Changes");
        SaveChangesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveChangesButton.setEnabled(false);
        SaveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveChangesButtonActionPerformed(evt);
            }
        });

        ResetButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ResetButton.setText("Reset");
        ResetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResetButton.setEnabled(false);
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        RemoveButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RemoveButton.setText("Remove");
        RemoveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RemoveButton.setEnabled(false);
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        ErrorLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        AddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AddressLabel.setText("Address");

        AddressTextArea.setEditable(false);
        AddressTextArea.setColumns(20);
        AddressTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddressTextArea.setRows(5);
        jScrollPane1.setViewportView(AddressTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(PhoneNOLabel)
                                .addGap(296, 296, 296))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(UsernameLabel)
                                        .addGap(12, 12, 12)
                                        .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(EmailLabel)
                                        .addGap(12, 12, 12)
                                        .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ICNOLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ICNOTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(GenderLabel)
                                    .addComponent(RoleLabel)
                                    .addComponent(RegisteredLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegisteredTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GenderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RoleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddressLabel)
                            .addComponent(CreditBalanceLabel))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CreditBalanceTextField)
                            .addComponent(PhoneNOTextField)
                            .addComponent(jScrollPane1)))
                    .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SaveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(RemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CustomerDetailsLabel)
                .addGap(362, 362, 362))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(CustomerDetailsLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(UsernameLabel)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(EmailLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ICNOLabel)
                            .addComponent(ICNOTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RoleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoleLabel))))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(PhoneNOLabel))
                        .addComponent(PhoneNOTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RegisteredTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RegisteredLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreditBalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenderLabel)
                    .addComponent(CreditBalanceLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddressLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveChangesButton)
                    .addComponent(ResetButton)
                    .addComponent(RemoveButton)
                    .addComponent(BackButton))
                .addGap(110, 110, 110))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BackButtonActionPerformed
        try {
            reset();
            Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
            f.AdminViewUserPanel.setAllCust();
            CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
            cardLayout.show(f.getControlPanel(), "adminViewCustPanel");
        } catch (ParseException ex) {
            Logger.getLogger(AdminViewUserDetailsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_BackButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ResetButtonActionPerformed
        ICNOTextField.setText(default_.getIcno());
        UsernameTextField.setText(default_.getUsername());
        RoleTextField.setText(default_.getRole());
        EmailTextField.setText(default_.getEmail());
        PhoneNOTextField.setText(default_.getPhone());
        GenderTextField.setText(default_.getGender());
        RegisteredTextField.setText(default_.getRegistered());
        CreditBalanceTextField.setText(default_.getCreditBalance());
        ErrorLabel.setText("");
    }// GEN-LAST:event_ResetButtonActionPerformed

    private void SaveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SaveChangesButtonActionPerformed
        try {
            String username = UsernameTextField.getText();
            String email = EmailTextField.getText();
            String phone = PhoneNOTextField.getText();

            UserValidator uv = new UserValidator();
            if (!uv.validateUsername(username)) {
                ErrorLabel.setText(uv.invalidUsername());
            } else if (!uv.validateUsernameLength(username)) {
                ErrorLabel.setText(uv.invalidUsernameLength());
            } else if (!uv.validateEmail(email)) {
                ErrorLabel.setText(uv.invalidEmail());
            } else if (!uv.validatePhone(phone)) {
                ErrorLabel.setText(uv.invalidPhone());
            } else {
                ErrorLabel.setText("");
                Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
                ManageAccProcess map = new ManageAccProcess();
                map.setAcc(default_.getIcno(), username, default_.getPassword(), default_.getRole(), email, phone,
                        default_.getGender(), default_.getAddress1(), default_.getAddress2(), default_.getCity(),
                        default_.getZip(), default_.getState(), default_.getRegistered(), default_.getCreditBalance(),
                        default_.getApproval());
                if (map.updateAcc()) {
                    f.AdminViewUserPanel.setAllCust();
                    CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
                    cardLayout.show(f.getControlPanel(), "adminViewCustPanel");
                } else {
                    JOptionPane.showMessageDialog(null, "Failed to update account.");
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(AdminViewUserDetailsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_SaveChangesButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RemoveButtonActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(null, "Confirm remove?", "WARNING",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
                ManageAccProcess map = new ManageAccProcess();
                if (map.removeAcc(default_.getIcno())) {
                    f.AdminViewUserPanel.setAllCust();
                    CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
                    cardLayout.show(f.getControlPanel(), "adminViewCustPanel");
                } else {
                    JOptionPane.showMessageDialog(null, "Failed to remove account.");
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(AdminViewUserDetailsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_RemoveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextArea AddressTextArea;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel CreditBalanceLabel;
    private javax.swing.JTextField CreditBalanceTextField;
    private javax.swing.JLabel CustomerDetailsLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JTextField GenderTextField;
    private javax.swing.JLabel ICNOLabel;
    private javax.swing.JTextField ICNOTextField;
    private javax.swing.JLabel PhoneNOLabel;
    private javax.swing.JTextField PhoneNOTextField;
    private javax.swing.JLabel RegisteredLabel;
    private javax.swing.JTextField RegisteredTextField;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JButton ResetButton;
    private javax.swing.JLabel RoleLabel;
    private javax.swing.JTextField RoleTextField;
    private javax.swing.JButton SaveChangesButton;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}