package UserInterface;

import Classes.State;
import Classes.UserRole;
import DAO.UserDao;
import Processes.RegisterProcess;
import Validator.UserValidator;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public final class AdminRegisterUserPanel extends javax.swing.JPanel {
    public AdminRegisterUserPanel() {
        initComponents();
        reset();
    }

    public void reset() {
        StateComboBox.setModel(new DefaultComboBoxModel(State.values()));
        UsernameTextField.setText("");
        ICNOTextField.setText("");
        PasswordTextField.setText("");
        ConfirmPasswordTextField.setText("");
        EmailTextField.setText("");
        PhoneNOTextField.setText("");
        GenderButtonGroup.clearSelection();
        AddressLine1TextField.setText("");
        AddressLine2TextField.setText("");
        CityTextField.setText("");
        ZIPCodeTextField.setText("");
        ErrorLabel.setText("");
    }

    public void setRoleComboBox() {
        if (UserDao.loggedIn.getRole().equals(UserRole.SUPERADMIN.toString())) {
            RoleComboBox.addItem(UserRole.ADMIN.toString());
            RoleComboBox.addItem(UserRole.CUSTOMER.toString());
            RoleComboBox.setEnabled(true);
        } else {
            RoleComboBox.addItem(UserRole.CUSTOMER.toString());
            RoleComboBox.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderButtonGroup = new javax.swing.ButtonGroup();
        NewUserLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        ICNOLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        PhoneNOLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        ICNOTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JPasswordField();
        ConfirmPasswordTextField = new javax.swing.JPasswordField();
        EmailTextField = new javax.swing.JTextField();
        PhoneNOTextField = new javax.swing.JTextField();
        MaleRadioButton = new javax.swing.JRadioButton();
        FemaleRadioButton = new javax.swing.JRadioButton();
        RegisterButton = new javax.swing.JButton();
        ErrorLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        AddressLine1Label = new javax.swing.JLabel();
        AddressLine1TextField = new javax.swing.JTextField();
        AddressLine2Label = new javax.swing.JLabel();
        AddressLine2TextField = new javax.swing.JTextField();
        CityLabel = new javax.swing.JLabel();
        CityTextField = new javax.swing.JTextField();
        ZIPCodeLabel = new javax.swing.JLabel();
        ZIPCodeTextField = new javax.swing.JTextField();
        StateLabel = new javax.swing.JLabel();
        StateComboBox = new javax.swing.JComboBox<>();
        RoleLabel = new javax.swing.JLabel();
        RoleComboBox = new javax.swing.JComboBox<>();

        NewUserLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        NewUserLabel.setText("New User");

        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UsernameLabel.setText("Username");

        ICNOLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ICNOLabel.setText("NRIC/Passport No.");

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PasswordLabel.setText("Password");

        ConfirmPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ConfirmPasswordLabel.setText("Confirm Password");

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmailLabel.setText("Email");

        PhoneNOLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PhoneNOLabel.setText("Phone No.");

        GenderLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GenderLabel.setText("Gender");

        UsernameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ICNOTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        PasswordTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ConfirmPasswordTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        EmailTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        PhoneNOTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        GenderButtonGroup.add(MaleRadioButton);
        MaleRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MaleRadioButton.setText("Male");
        MaleRadioButton.setActionCommand("M");
        MaleRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        GenderButtonGroup.add(FemaleRadioButton);
        FemaleRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FemaleRadioButton.setText("Female");
        FemaleRadioButton.setActionCommand("F");

        RegisterButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        RegisterButton.setText("Register");
        RegisterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        ErrorLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ErrorLabel.setForeground(new java.awt.Color(255, 51, 51));

        BackButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BackButton.setText("Back");
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        AddressLine1Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AddressLine1Label.setText("Address Line 1");

        AddressLine1TextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        AddressLine2Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AddressLine2Label.setText("Address Line 2");

        AddressLine2TextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CityLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CityLabel.setText("City");

        CityTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ZIPCodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ZIPCodeLabel.setText("ZIP/Postal Code");

        ZIPCodeTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        StateLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        StateLabel.setText("State");

        StateComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        RoleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RoleLabel.setText("Role");

        RoleComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RoleComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RoleComboBox.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(395, 395, 395)
                                                .addComponent(NewUserLabel))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addComponent(UsernameLabel)
                                                .addGap(5, 5, 5)
                                                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(23, 23, 23)
                                                .addComponent(ICNOLabel)
                                                .addGap(5, 5, 5)
                                                .addComponent(ICNOTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(81, 81, 81)
                                                .addComponent(PasswordLabel)
                                                .addGap(5, 5, 5)
                                                .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(129, 129, 129)
                                                .addComponent(EmailLabel)
                                                .addGap(5, 5, 5)
                                                .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(ConfirmPasswordLabel)
                                                .addGap(5, 5, 5)
                                                .addComponent(ConfirmPasswordTextField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 246,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(90, 90, 90)
                                                .addComponent(PhoneNOLabel)
                                                .addGap(5, 5, 5)
                                                .addComponent(PhoneNOTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(AddressLine1Label)
                                                .addGap(5, 5, 5)
                                                .addComponent(AddressLine1TextField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 246,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(114, 114, 114)
                                                .addComponent(GenderLabel)
                                                .addGap(5, 5, 5)
                                                .addComponent(MaleRadioButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(FemaleRadioButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(AddressLine2Label)
                                                .addGap(5, 5, 5)
                                                .addComponent(AddressLine2TextField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 246,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(143, 143, 143)
                                                .addComponent(CityLabel)
                                                .addGap(5, 5, 5)
                                                .addComponent(CityTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(166, 166, 166)
                                                .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        600, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(166, 166, 166)
                                                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 600,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(RoleLabel)
                                                        .addComponent(ZIPCodeLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ZIPCodeTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 246,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(RoleComboBox,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 149,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(132, 132, 132)
                                                                .addComponent(StateLabel)
                                                                .addGap(5, 5, 5)
                                                                .addComponent(StateComboBox,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 250,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(ErrorLabel,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 670,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(61, 61, 61)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(NewUserLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ICNOTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(UsernameLabel)
                                                        .addComponent(ICNOLabel))))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(PasswordLabel)
                                                        .addComponent(EmailLabel))))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ConfirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PhoneNOTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ConfirmPasswordLabel)
                                                        .addComponent(PhoneNOLabel))))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(AddressLine1Label))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(AddressLine1TextField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(GenderLabel))
                                        .addComponent(MaleRadioButton)
                                        .addComponent(FemaleRadioButton))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AddressLine2TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CityTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(AddressLine2Label)
                                                        .addComponent(CityLabel))))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(ZIPCodeLabel))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(ZIPCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(StateLabel))
                                        .addComponent(StateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(RoleComboBox,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(RoleLabel))))
                                .addGap(44, 44, 44)
                                .addComponent(RegisterButton)
                                .addGap(9, 9, 9)
                                .addComponent(BackButton)
                                .addGap(95, 95, 95)));
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RegisterButtonActionPerformed
        try {
            String username = UsernameTextField.getText();
            String icno = ICNOTextField.getText();
            String password = new String(PasswordTextField.getPassword());
            String confirmPassword = new String(ConfirmPasswordTextField.getPassword());
            String email = EmailTextField.getText();
            String phone = PhoneNOTextField.getText();
            String address1 = AddressLine1TextField.getText();
            String address2 = AddressLine2TextField.getText();
            String city = CityTextField.getText();
            String zip = ZIPCodeTextField.getText();
            String state = StateComboBox.getSelectedItem().toString();
            String role = RoleComboBox.getSelectedItem().toString();

            UserValidator uv = new UserValidator();
            if (!username.trim().equals("") || !icno.trim().equals("") || !password.trim().equals("")
                    || !confirmPassword.trim().equals("") || !email.trim().equals("") || !phone.trim().equals("")
                    || !address1.trim().equals("") || !city.trim().equals("") || !zip.trim().equals("")) {
                if (GenderButtonGroup.getSelection() != null) {
                    ErrorLabel.setText("");
                    String gender = GenderButtonGroup.getSelection().getActionCommand();
                    if (!uv.validateUsername(username)) {
                        ErrorLabel.setText(uv.invalidUsername());
                    } else if (!uv.validateUsernameLength(username)) {
                        ErrorLabel.setText(uv.invalidUsernameLength());
                    } else if (!uv.validateICNO(icno)) {
                        ErrorLabel.setText(uv.invalidICNO());
                    } else if (!uv.validatePassword(password)) {
                        ErrorLabel.setText(uv.invalidPassword());
                    } else if (!uv.validatePasswordLength(password)) {
                        ErrorLabel.setText(uv.invalidPasswordLength());
                    } else if (!uv.validateConfirmPassword(password, confirmPassword)) {
                        ErrorLabel.setText(uv.invalidConfirmPassword());
                    } else if (!uv.validateEmail(email)) {
                        ErrorLabel.setText(uv.invalidEmail());
                    } else if (!uv.validatePhone(phone)) {
                        ErrorLabel.setText(uv.invalidPhone());
                    } else if (!uv.validateCity(city)) {
                        ErrorLabel.setText(uv.invalidCity());
                    } else if (!uv.validateZIP(zip)) {
                        ErrorLabel.setText(uv.invalidZIP());
                    } else {
                        // replace , with : so that it doesn't confused with separator
                        String newAddress1 = address1.replace(",", ":");
                        String newAddress2 = address2.replace(",", ":");

                        RegisterProcess rp = new RegisterProcess(username, icno, password, email, phone, gender,
                                newAddress1, newAddress2, city, zip, state);
                        if (rp.userExisted()) {
                            ErrorLabel.setText(rp.userExistedMessage());
                        } else {
                            ErrorLabel.setText("");
                            if (rp.registerSuccess(role, "YES")) {
                                reset();
                                JOptionPane.showMessageDialog(null, "Registration complete!");

                                Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
                                f.AdminViewUserPanel.setAllCust();
                                CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
                                cardLayout.show(f.getControlPanel(), "adminViewCustPanel");
                            }
                        }
                    }
                } else {
                    ErrorLabel.setText(uv.required());
                }
            } else {
                ErrorLabel.setText(uv.required());
            }
        } catch (ParseException ex) {
            Logger.getLogger(AdminViewUserDetailsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_RegisterButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BackButtonActionPerformed
        try {
            reset();
            Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
            f.AdminViewUserPanel.setAllCust();
            CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
            cardLayout.show(f.getControlPanel(), "adminViewCustPanel");
        } catch (ParseException ex) {
            Logger.getLogger(AdminViewUserDetailsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_BackButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLine1Label;
    private javax.swing.JTextField AddressLine1TextField;
    private javax.swing.JLabel AddressLine2Label;
    private javax.swing.JTextField AddressLine2TextField;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JTextField CityTextField;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JPasswordField ConfirmPasswordTextField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JRadioButton FemaleRadioButton;
    private javax.swing.ButtonGroup GenderButtonGroup;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel ICNOLabel;
    private javax.swing.JTextField ICNOTextField;
    private javax.swing.JRadioButton MaleRadioButton;
    private javax.swing.JLabel NewUserLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JLabel PhoneNOLabel;
    private javax.swing.JTextField PhoneNOTextField;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JComboBox<String> RoleComboBox;
    private javax.swing.JLabel RoleLabel;
    private javax.swing.JComboBox<String> StateComboBox;
    private javax.swing.JLabel StateLabel;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel ZIPCodeLabel;
    private javax.swing.JTextField ZIPCodeTextField;
    // End of variables declaration//GEN-END:variables
}