package UserInterface;

import Classes.Booking;
import DAO.BookingDao;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

public class AdminReturnCarPanel extends javax.swing.JPanel {
    DefaultTableModel model;
    ArrayList<Booking> bookings;
    private String select;
    
    public AdminReturnCarPanel() {
        initComponents();
        model = (DefaultTableModel) ReturnCarTable.getModel();
    }

    public void setTable() {
        reset();
        String[] columnName = {"Car", "Booking", "Status", "Customer"};
        model.setColumnIdentifiers(columnName);
        ReturnCarTable.setDefaultEditor(Object.class, null);
        ReturnCarTable.getTableHeader().setResizingAllowed(false);
        
        BookingDao bookingDao = new BookingDao();
        bookings = bookingDao.getApproved();
        
        if (bookings != null) {
            for (Booking booking : bookings) {
                String[] tableRow = {booking.getCarId(), booking.getBookingId(), booking.getStatus(), booking.getCustomerId()};
                model.addRow(tableRow);
            }
        }
    }
    
    public void reset() {
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        
        ReturnButton.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ReturnCarTable = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();
        ReturnButton = new javax.swing.JButton();

        ReturnCarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ReturnCarTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnCarTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ReturnCarTable);

        BackButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BackButton.setText("Back");
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        ReturnButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ReturnButton.setText("Return");
        ReturnButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReturnButton.setEnabled(false);
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton)
                    .addComponent(ReturnButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
        CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
        cardLayout.show(f.getControlPanel(), "adminHomePanel");
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ReturnCarTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnCarTableMouseClicked
        javax.swing.JTable target = (javax.swing.JTable) evt.getSource();
        int row = target.getSelectedRow();
        select = ReturnCarTable.getValueAt(row, 1).toString();
        ReturnButton.setEnabled(true);
    }//GEN-LAST:event_ReturnCarTableMouseClicked

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        Frame currentJFrame = (Frame) SwingUtilities.getWindowAncestor(this);
        String returned = "Car has been returned. Completed.";
        Booking approving;
        BookingDao bookingDao = new BookingDao();
        approving = bookingDao.get(select);
        approving.setStatus(returned);
        
        Integer[] options = {1,2,3,4,5};
        int ratingIndex = JOptionPane.showOptionDialog(null, "Please give a rating for the experience. (Default to 3)",
                "Rating",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[2]);
        
        String rating = Integer.toString(ratingIndex + 1);
        if (rating.equals("0")) {
            approving.setRating("3");
        } else {
            approving.setRating(rating);
        }
        
        if (bookingDao.update(select, approving)) {
            setTable();
            BookingListingPanel bookingListingPanel = currentJFrame.bookingListingPanel;
            bookingListingPanel.buildTable(null, false, false);
        } 
        else{
            JOptionPane.showMessageDialog(null, "Failed to return car.");
        }
    }//GEN-LAST:event_ReturnButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JTable ReturnCarTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
