package UserInterface;

import DAO.UserDao;
import Processes.LogoutProcess;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class AdminHomePanel extends javax.swing.JPanel {
    public AdminHomePanel() {
        initComponents();
    }

    // public LoggedIn user() {
    // Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
    // return f.getLoggedIn();
    // }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProfileButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        ManageCustomerButton = new javax.swing.JButton();
        ManageBookingButton = new javax.swing.JButton();
        ManageCarButton = new javax.swing.JButton();
        GenerateReportButton = new javax.swing.JButton();
        ReturnCarButton = new javax.swing.JButton();

        ProfileButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ProfileButton.setText("Profile");
        ProfileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileButtonActionPerformed(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        ManageCustomerButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ManageCustomerButton.setText("Manage User");
        ManageCustomerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCustomerButtonActionPerformed(evt);
            }
        });

        ManageBookingButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ManageBookingButton.setText("Manage Booking");
        ManageBookingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageBookingButtonActionPerformed(evt);
            }
        });

        ManageCarButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ManageCarButton.setText("Manage Car");
        ManageCarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCarButtonActionPerformed(evt);
            }
        });

        GenerateReportButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        GenerateReportButton.setText("Generate Report");
        GenerateReportButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GenerateReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReportButtonActionPerformed(evt);
            }
        });

        ReturnCarButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ReturnCarButton.setText("Return Car");
        ReturnCarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReturnCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnCarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(ProfileButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 666,
                                        Short.MAX_VALUE)
                                .addComponent(LogoutButton)
                                .addGap(33, 33, 33))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(325, 325, 325)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(GenerateReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 229,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(ManageCarButton,
                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ManageBookingButton,
                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ManageCustomerButton,
                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ReturnCarButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ProfileButton)
                                        .addComponent(LogoutButton))
                                .addGap(83, 83, 83)
                                .addComponent(ManageCustomerButton)
                                .addGap(18, 18, 18)
                                .addComponent(ManageBookingButton)
                                .addGap(18, 18, 18)
                                .addComponent(ManageCarButton)
                                .addGap(18, 18, 18)
                                .addComponent(ReturnCarButton)
                                .addGap(18, 18, 18)
                                .addComponent(GenerateReportButton)
                                .addContainerGap(173, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void ManageBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ManageBookingButtonActionPerformed
        Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
        CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
        f.bookingListingPanel.buildTable(null, false, false);
        cardLayout.show(f.getControlPanel(), "bookingListingPanel");
    }// GEN-LAST:event_ManageBookingButtonActionPerformed

    private void ManageCarButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ManageCarButtonActionPerformed
        Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
        CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
        f.carListingPanel.buildTable(null);
        cardLayout.show(f.getControlPanel(), "carListingPanel");
    }// GEN-LAST:event_ManageCarButtonActionPerformed

    private void GenerateReportButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_GenerateReportButtonActionPerformed
        Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
        CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
        cardLayout.show(f.getControlPanel(), "reportMenuPanel");
    }// GEN-LAST:event_GenerateReportButtonActionPerformed

    private void ReturnCarButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ReturnCarButtonActionPerformed
        Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
        f.AdminReturnCarPanel.setTable();
        CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
        cardLayout.show(f.getControlPanel(), "adminReturnCarPanel");
    }// GEN-LAST:event_ReturnCarButtonActionPerformed

    private void ProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ProfileButtonActionPerformed
        Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
        f.ProfilePanel.getProfile(UserDao.loggedIn);
        CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
        cardLayout.show(f.getControlPanel(), "profilePanel");
    }// GEN-LAST:event_ProfileButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LogoutButtonActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirm logout?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
            LogoutProcess lp = new LogoutProcess();
            lp.logout(f);
        }
    }// GEN-LAST:event_LogoutButtonActionPerformed

    private void ManageCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ManageCustomerButtonActionPerformed
        try {
            Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
            f.AdminViewUserPanel.setAllCust();
            CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
            cardLayout.show(f.getControlPanel(), "adminViewCustPanel");
        } catch (ParseException ex) {
            Logger.getLogger(AdminHomePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_ManageCustomerButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerateReportButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ManageBookingButton;
    private javax.swing.JButton ManageCarButton;
    private javax.swing.JButton ManageCustomerButton;
    private javax.swing.JButton ProfileButton;
    private javax.swing.JButton ReturnCarButton;
    // End of variables declaration//GEN-END:variables
}