package UserInterface;

import Classes.Booking;
import Classes.UserRole;
import DAO.PaymentDao;
import DAO.UserDao;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public class BookingDetailPanel extends javax.swing.JPanel {
    Booking default_;
    
    public BookingDetailPanel() {
        initComponents();
    }

    public void setBookingDetail(String bookingId) {
        Booking booking = new Booking(bookingId);

        bookingIdLabel.setText(booking.getBookingId());
        customerIdLabel.setText(booking.getCustomerId());
        adminIdLabel.setText(booking.getAdminId());
        carIdLabel.setText(booking.getCarId());
        bookingDurationLabel.setText(booking.getBookingDuration());
        statusLabel.setText(booking.getStatus());
        bookingDateLabel.setText(booking.getBookingDate());
        String capitalizedPaymentStatus = booking.getPayment().getApproval();
        paymentButton.setText(capitalizedPaymentStatus + ". Click to view more.");
        
        this.default_ = booking;
        
        
        approveButton.setVisible(true);
        editButton.setVisible(true);
        deleteButton.setVisible(true);
        
        if (booking.getStatus().equals("approved")) {
            approveButton.setVisible(false);
            editButton.setVisible(false);
        } 
        
        if (UserDao.loggedIn.getRole().equals(UserRole.CUSTOMER.toString())) {
            editButton.setVisible(false);
            approveButton.setVisible(false);
            deleteButton.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bookingIdLabel = new javax.swing.JLabel();
        customerIdLabel = new javax.swing.JLabel();
        adminIdLabel = new javax.swing.JLabel();
        carIdLabel = new javax.swing.JLabel();
        bookingDurationLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        bookingDateLabel = new javax.swing.JLabel();
        paymentButton = new javax.swing.JButton();
        approveButton = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Booking Detail");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridLayout(8, 1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Booking ID");
        jPanel2.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Customer ID");
        jPanel2.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Admin ID");
        jPanel2.add(jLabel11);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Car ID");
        jPanel2.add(jLabel12);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("Booking Duration");
        jPanel2.add(jLabel13);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("Status");
        jPanel2.add(jLabel14);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setText("Booking Date");
        jPanel2.add(jLabel15);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Payment Status");
        jPanel2.add(jLabel3);

        jPanel3.setLayout(new java.awt.GridLayout(8, 1));

        bookingIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bookingIdLabel.setText("Booking ID");
        jPanel3.add(bookingIdLabel);

        customerIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        customerIdLabel.setText("Customer ID");
        jPanel3.add(customerIdLabel);

        adminIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        adminIdLabel.setText("Admin ID");
        jPanel3.add(adminIdLabel);

        carIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        carIdLabel.setText("Car ID");
        jPanel3.add(carIdLabel);

        bookingDurationLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bookingDurationLabel.setText("Booking Duration");
        jPanel3.add(bookingDurationLabel);

        statusLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        statusLabel.setText("Status");
        jPanel3.add(statusLabel);

        bookingDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bookingDateLabel.setText("Booking Date");
        jPanel3.add(bookingDateLabel);

        paymentButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        paymentButton.setText("Not Completed. Click to view more.");
        paymentButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        paymentButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        paymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentButtonActionPerformed(evt);
            }
        });
        jPanel3.add(paymentButton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        approveButton.setText("Approve");
        approveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(approveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(approveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void approveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveButtonActionPerformed
        Frame currentJFrame = (Frame) SwingUtilities.getWindowAncestor(this);
        JPanel controlPanel = currentJFrame.getControlPanel();
        CardLayout layout = (CardLayout) controlPanel.getLayout();

        Booking booking = new Booking();
        boolean isBookingApprovalSuccessful = booking.approve(bookingIdLabel.getText());

        if (isBookingApprovalSuccessful) { 
            BookingListingPanel bookingListingPanel = currentJFrame.bookingListingPanel;
            bookingListingPanel.buildTable(null, false, false);
            layout.show(controlPanel, "bookingListingPanel");
            JOptionPane.showMessageDialog(currentJFrame, "The booking has been approved successfully.");
        } else {
            JOptionPane.showMessageDialog(currentJFrame, "Failed to approve this booking.");
        }
    }//GEN-LAST:event_approveButtonActionPerformed

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
        Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
        f.AdminViewPaymentDetailsPanel.getPaymentId(default_.getPayment().getPaymentId());
        CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
        cardLayout.show(f.getControlPanel(), "adminViewPaymentDetailsPanel");
    }//GEN-LAST:event_paymentButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        Frame currentJFrame = (Frame) SwingUtilities.getWindowAncestor(this);
        JPanel controlPanel = currentJFrame.getControlPanel();
        CardLayout layout = (CardLayout) controlPanel.getLayout();

        if (UserDao.loggedIn.getRole().equals(UserRole.CUSTOMER.toString())) {
            layout.show(controlPanel, "bookingHistoryPanel");
        }
        else {
            layout.show(controlPanel, "bookingListingPanel");
        }
    }// GEN-LAST:event_backButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        Frame currentJFrame = (Frame) SwingUtilities.getWindowAncestor(this);
        JPanel controlPanel = currentJFrame.getControlPanel();
        CardLayout layout = (CardLayout) controlPanel.getLayout();

        currentJFrame.bookingEditingPanel.setBookingDetail(bookingIdLabel.getText());
        layout.show(controlPanel, "bookingEditingPanel");
    }// GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        Frame currentJFrame = (Frame) SwingUtilities.getWindowAncestor(this);
        JPanel controlPanel = currentJFrame.getControlPanel();
        CardLayout layout = (CardLayout) controlPanel.getLayout();

        Booking booking = new Booking();
        boolean isBookingDeletionSuccessful = booking.delete(bookingIdLabel.getText());
        if (isBookingDeletionSuccessful) {
            BookingListingPanel bookingListingPanel = currentJFrame.bookingListingPanel;
            bookingListingPanel.buildTable(null, false, false);
            layout.show(controlPanel, "bookingListingPanel");
            JOptionPane.showMessageDialog(currentJFrame, "The booking has been deleted successfully.");
        } else {
            JOptionPane.showMessageDialog(currentJFrame, "Failed to delete this booking.");
        }
    }// GEN-LAST:event_deleteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminIdLabel;
    private javax.swing.JButton approveButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bookingDateLabel;
    private javax.swing.JLabel bookingDurationLabel;
    private javax.swing.JLabel bookingIdLabel;
    private javax.swing.JLabel carIdLabel;
    private javax.swing.JLabel customerIdLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton paymentButton;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
