package UserInterface;

import Classes.CreditBalanceDetail;
import Classes.TimeGranularity;
import Classes.User;
import DAO.CreditBalanceDetailDao;
import Validator.PaymentValidator;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

public class CreditBalancePanel extends javax.swing.JPanel {
    DefaultTableModel model;
    private User user;

    public CreditBalancePanel() {
        initComponents();
        model = (DefaultTableModel) CreditBalanceDetailsTable.getModel();
    }

    public void setCreditBalance(User user) {
        CreditBalanceTextField.setText(user.getCreditBalance());
        this.user = user;
    }

    public void setCreditBalanceDetails() throws ParseException {
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }

        String[] columnName = { "Date", "Amount", "Remaining Balance" };
        model.setColumnIdentifiers(columnName);
        CreditBalanceDetailsTable.setDefaultEditor(Object.class, null);
        CreditBalanceDetailsTable.getTableHeader().setResizingAllowed(false);

        CreditBalanceDetailDao creditBalanceDetailDao = new CreditBalanceDetailDao();
        ArrayList<CreditBalanceDetail> details = creditBalanceDetailDao.searchUser(user.getIcno());

        TimeGranularity tg = new TimeGranularity();
        for (CreditBalanceDetail detail : details) {
            tg.setGranularity(detail.getDatetime());
            String flow = detail.getFlow().equals("IN") ? "+" : "-";
            String[] row = { tg.getGranularity(), flow + " " + detail.getAmount(), detail.getFinalAmount() };
            model.addRow(row);
        }
    }

    public void reset() {
        CreditBalanceTextField.setText("");
        ReloadAmountTextField.setText("");
        ErrorLabel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CurrentBalanceLabel = new javax.swing.JLabel();
        CreditBalanceTextField = new javax.swing.JTextField();
        ReloadButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CreditBalanceDetailsTable = new javax.swing.JTable();
        ReloadAmountLabel = new javax.swing.JLabel();
        ReloadAmountTextField = new javax.swing.JTextField();
        ErrorLabel = new javax.swing.JLabel();

        CurrentBalanceLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CurrentBalanceLabel.setText("Current Balance");

        CreditBalanceTextField.setEditable(false);
        CreditBalanceTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ReloadButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ReloadButton.setText("Reload");
        ReloadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReloadButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BackButton.setText("Back");
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        CreditBalanceDetailsTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreditBalanceDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {

                }));
        jScrollPane1.setViewportView(CreditBalanceDetailsTable);

        ReloadAmountLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ReloadAmountLabel.setText("Reload Amount");

        ReloadAmountTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ErrorLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
        ErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jScrollPane1))
                                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(CurrentBalanceLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CreditBalanceTextField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 152,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(ErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addComponent(ReloadAmountLabel)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(ReloadAmountTextField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 152,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(ReloadButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 124,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(43, 43, 43)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(CurrentBalanceLabel)
                                        .addComponent(CreditBalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ReloadAmountLabel)
                                        .addComponent(ReloadAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ReloadButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BackButton)
                                .addContainerGap(81, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BackButtonActionPerformed
        reset();
        Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
        CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
        cardLayout.show(f.getControlPanel(), "custHomePanel");
    }// GEN-LAST:event_BackButtonActionPerformed

    private void ReloadButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ReloadButtonActionPerformed
        String reloadAmount = ReloadAmountTextField.getText();
        PaymentValidator pv = new PaymentValidator();
        if (!reloadAmount.trim().equals("")) {
            ErrorLabel.setText("");
            if (!pv.validateCreditAmount(reloadAmount)) {
                ErrorLabel.setText(pv.invalidCreditAmount());
            } else {
                ErrorLabel.setText("");
                reset();
                Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
                f.ReloadCreditBalancePanel.setReloadAmount(reloadAmount);
                CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
                cardLayout.show(f.getControlPanel(), "reloadCreditBalancePanel");
            }
        }
    }// GEN-LAST:event_ReloadButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTable CreditBalanceDetailsTable;
    private javax.swing.JTextField CreditBalanceTextField;
    private javax.swing.JLabel CurrentBalanceLabel;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JLabel ReloadAmountLabel;
    private javax.swing.JTextField ReloadAmountTextField;
    private javax.swing.JButton ReloadButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}