package UserInterface;

import DAO.UserDao;
import Processes.LogoutProcess;
import java.awt.CardLayout;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public final class CustHomePanel extends javax.swing.JPanel {
    public CustHomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProfileButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        CreditBalaneButton = new javax.swing.JButton();
        BookingHistoryButton = new javax.swing.JButton();
        CreateBookingButton = new javax.swing.JButton();

        ProfileButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ProfileButton.setText("Profile");
        ProfileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileButtonActionPerformed(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        CreditBalaneButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CreditBalaneButton.setText("Credit Balance");
        CreditBalaneButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CreditBalaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditBalaneButtonActionPerformed(evt);
            }
        });

        BookingHistoryButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BookingHistoryButton.setText("Booking History");
        BookingHistoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BookingHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingHistoryButtonActionPerformed(evt);
            }
        });

        CreateBookingButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CreateBookingButton.setText("Create Booking");
        CreateBookingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CreateBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBookingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ProfileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 674, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BookingHistoryButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CreateBookingButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreditBalaneButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfileButton)
                    .addComponent(LogoutButton))
                .addGap(143, 143, 143)
                .addComponent(CreditBalaneButton)
                .addGap(18, 18, 18)
                .addComponent(CreateBookingButton)
                .addGap(18, 18, 18)
                .addComponent(BookingHistoryButton)
                .addContainerGap(228, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BookingHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingHistoryButtonActionPerformed
        Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
        f.bookingHistoryPanel.buildTable(null, false, false);
        CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
        cardLayout.show(f.getControlPanel(), "bookingHistoryPanel");
    }//GEN-LAST:event_BookingHistoryButtonActionPerformed

    private void CreateBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBookingButtonActionPerformed
        Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
        CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
        cardLayout.show(f.getControlPanel(), "bookingCreatingPanel");
    }//GEN-LAST:event_CreateBookingButtonActionPerformed

    private void ProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ProfileButtonActionPerformed
        Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
        f.ProfilePanel.getProfile(UserDao.loggedIn);
        CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
        cardLayout.show(f.getControlPanel(), "profilePanel");
    }// GEN-LAST:event_ProfileButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LogoutButtonActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirm logout?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
            LogoutProcess lp = new LogoutProcess();
            lp.logout(f);
        }
    }// GEN-LAST:event_LogoutButtonActionPerformed

    private void CreditBalaneButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CreditBalaneButtonActionPerformed
        Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
        f.CreditBalancePanel.setCreditBalance(UserDao.loggedIn);
        try {
            f.CreditBalancePanel.setCreditBalanceDetails();
        } catch (ParseException ex) {}
        
        CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
        cardLayout.show(f.getControlPanel(), "creditBalancePanel");
    }// GEN-LAST:event_CreditBalaneButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookingHistoryButton;
    private javax.swing.JButton CreateBookingButton;
    private javax.swing.JButton CreditBalaneButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ProfileButton;
    // End of variables declaration//GEN-END:variables
}