package UserInterface;

import Classes.Current;
import Classes.LoggedIn;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import carrentalsystem.Environment;
import java.util.HashMap;

public class Frame extends Environment {
    private LoggedIn user = null;

    public Frame() throws InterruptedException {
        initComponents();

        setTitle("Car Rental System");
        setSize(900, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        HashMap<String, JPanel> allPanels = this.getAllPanels();
        for (String panelName : allPanels.keySet()) {
            ControlPanel.add(panelName, allPanels.get(panelName));
        }

        CardLayout cardLayout = (CardLayout) ControlPanel.getLayout();
        cardLayout.show(ControlPanel, "homePanel");

        Current c = new Current();
        CurrentLabel.setText(c.date);
    }

    public JPanel getControlPanel() {
        return ControlPanel;
    }

    public void setLoggedIn(LoggedIn user) {
        this.user = user;
    }

    public LoggedIn getLoggedIn() {
        return user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DateTimeHeader = new javax.swing.JPanel();
        CurrentLabel = new javax.swing.JLabel();
        ControlPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DateTimeHeader.setToolTipText("");
        DateTimeHeader.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        CurrentLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CurrentLabel.setText("DATETIME");
        DateTimeHeader.add(CurrentLabel);

        getContentPane().add(DateTimeHeader, java.awt.BorderLayout.PAGE_START);

        ControlPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(ControlPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Frame().setVisible(true);
            } catch (InterruptedException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel ControlPanel;
    private static javax.swing.JLabel CurrentLabel;
    private static javax.swing.JPanel DateTimeHeader;
    // End of variables declaration//GEN-END:variables
}
