package UserInterface;

import Classes.UserRole;
import DAO.UserDao;
import Processes.LoginProcess;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class LoginPanel extends javax.swing.JPanel {
    public LoginPanel() {
        initComponents();
    }

    public void reset() {
        ICNOTextField.setText("");
        PasswordTextField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginLabel = new javax.swing.JLabel();
        ICNOLabel = new javax.swing.JLabel();
        ICNOTextField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordTextField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        RegisterLabel = new javax.swing.JLabel();

        LoginLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LoginLabel.setText("Login");

        ICNOLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ICNOLabel.setText("NRIC/Passport No.");

        ICNOTextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PasswordLabel.setText("Password");

        PasswordTextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        LoginButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        RegisterLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RegisterLabel.setText("Register an account");
        RegisterLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(113, 113, 113)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(PasswordLabel)
                                                        .addComponent(ICNOLabel))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(PasswordTextField,
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(ICNOTextField)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                .createSequentialGroup()
                                                .addGap(210, 210, 210)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(RegisterLabel)
                                                                .addGap(0, 358, Short.MAX_VALUE))
                                                        .addComponent(LoginButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE))))
                                .addGap(170, 170, 170))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(LoginLabel)
                                .addGap(399, 399, 399)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(LoginLabel)
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ICNOLabel)
                                        .addComponent(ICNOTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(PasswordLabel)
                                        .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(LoginButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RegisterLabel)
                                .addContainerGap(223, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LoginButtonActionPerformed
        String icno = ICNOTextField.getText();
        String password = new String(PasswordTextField.getPassword());

        if (!icno.trim().equals("") && !password.trim().equals("")) {
            LoginProcess lp = new LoginProcess();
            lp.setLogin(icno, password);

            if (lp.getLogin()) {
                JOptionPane.showMessageDialog(null, "Welcome " + UserDao.loggedIn.getUsername());

                reset();
                Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
                String role = UserDao.loggedIn.getRole();

                if (role.equals(UserRole.CUSTOMER.toString())) {
                    CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
                    cardLayout.show(f.getControlPanel(), "custHomePanel");
                } else if (role.equals(UserRole.ADMIN.toString()) | role.equals(UserRole.SUPERADMIN.toString())) {
                    CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
                    cardLayout.show(f.getControlPanel(), "adminHomePanel");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Login Failed");
                reset();
            }
        }
    }// GEN-LAST:event_LoginButtonActionPerformed

    private void RegisterLabelMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_RegisterLabelMouseClicked
        reset();

        Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
        CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
        cardLayout.show(f.getControlPanel(), "registerPanel");
    }// GEN-LAST:event_RegisterLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ICNOLabel;
    private javax.swing.JTextField ICNOTextField;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JLabel RegisterLabel;
    // End of variables declaration//GEN-END:variables
}