package UserInterface;

import Classes.User;
import Classes.UserRole;
import DAO.UserDao;
import Processes.LogoutProcess;
import Processes.ProfileProcess;
import Validator.UserValidator;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class ProfilePanel extends javax.swing.JPanel {
    private User user;
    private String old_username, old_email, old_phone;

    public ProfilePanel() {
        initComponents();
    }

    public void getProfile(User user) {
        ICNOTextField.setText(user.getIcno());
        UsernameTextField.setText(user.getUsername());
        RoleTextField.setText(user.getRole());
        EmailTextField.setText(user.getEmail());
        PhoneNOTextField.setText(user.getPhone());
        GenderTextField.setText(user.getGender());
        AddressTextArea.setText(user.getAddress1().replace(":", ",") + "\n" + user.getAddress2().replace(":", ",")
                + "\n" + user.getCity() + "\n" + user.getZip() + "\n" + user.getState());
        RegisteredTextField.setText(user.getRegistered());

        old_username = user.getUsername();
        old_email = user.getEmail();
        old_phone = user.getPhone();
        
        this.user = user;
    }

    public void reset() {
        PasswordTextField.setText("");
        ConfirmPasswordTextField.setText("");
        ErrorLabel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProfileLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        ICNOLabel = new javax.swing.JLabel();
        ICNOTextField = new javax.swing.JTextField();
        RoleLabel = new javax.swing.JLabel();
        RoleTextField = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        PhoneNOLabel = new javax.swing.JLabel();
        PhoneNOTextField = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        GenderTextField = new javax.swing.JTextField();
        RegisteredLabel = new javax.swing.JLabel();
        RegisteredTextField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordTextField = new javax.swing.JPasswordField();
        SaveChangesButton = new javax.swing.JButton();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        ConfirmPasswordTextField = new javax.swing.JPasswordField();
        ErrorLabel = new javax.swing.JLabel();
        ResetButton = new javax.swing.JButton();
        AddressLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressTextArea = new javax.swing.JTextArea();

        ProfileLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ProfileLabel.setText("Profile");

        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UsernameLabel.setText("Username");

        UsernameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ICNOLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ICNOLabel.setText("NRIC/Passport No.");

        ICNOTextField.setEditable(false);
        ICNOTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        RoleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RoleLabel.setText("Role");

        RoleTextField.setEditable(false);
        RoleTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmailLabel.setText("Email");

        EmailTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        PhoneNOLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PhoneNOLabel.setText("Phone No.");

        PhoneNOTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        GenderLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GenderLabel.setText("Gender");

        GenderTextField.setEditable(false);
        GenderTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        RegisteredLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RegisteredLabel.setText("Registered");

        RegisteredTextField.setEditable(false);
        RegisteredTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PasswordLabel.setText("Password");
        PasswordLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PasswordTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        SaveChangesButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SaveChangesButton.setText("Save Changes");
        SaveChangesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveChangesButtonActionPerformed(evt);
            }
        });

        ConfirmPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ConfirmPasswordLabel.setText("Confirm Password");

        ConfirmPasswordTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ErrorLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ErrorLabel.setForeground(new java.awt.Color(255, 51, 51));

        ResetButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ResetButton.setText("Reset");
        ResetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        AddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AddressLabel.setText("Address");

        AddressTextArea.setEditable(false);
        AddressTextArea.setColumns(20);
        AddressTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddressTextArea.setRows(5);
        jScrollPane1.setViewportView(AddressTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(457, 457, 457)
                .addComponent(ProfileLabel))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(UsernameLabel)
                .addGap(5, 5, 5)
                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(ICNOLabel)
                .addGap(9, 9, 9)
                .addComponent(ICNOTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(EmailLabel)
                .addGap(5, 5, 5)
                .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(RoleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RoleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(PhoneNOLabel)
                .addGap(5, 5, 5)
                .addComponent(PhoneNOTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(RegisteredLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegisteredTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(PasswordLabel)
                .addGap(5, 5, 5)
                .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addComponent(GenderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ConfirmPasswordLabel)
                .addGap(5, 5, 5)
                .addComponent(ConfirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(AddressLabel)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(ProfileLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(UsernameLabel))
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(ICNOLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(ICNOTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(EmailLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RoleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RoleLabel)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(PhoneNOLabel))
                    .addComponent(PhoneNOTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RegisteredTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RegisteredLabel)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(PasswordLabel))
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GenderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenderLabel))))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(ConfirmPasswordLabel))
                    .addComponent(ConfirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddressLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(SaveChangesButton)
                        .addGap(7, 7, 7)
                        .addComponent(ResetButton))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SaveChangesButtonActionPerformed
        String username = UsernameTextField.getText();
        String email = EmailTextField.getText();
        String old_password = user.getPassword();
        String password = new String(PasswordTextField.getPassword());
        String confirmPassword = new String(ConfirmPasswordTextField.getPassword());
        String phone = PhoneNOTextField.getText();
        boolean logout;

        confirmPassword = new String(ConfirmPasswordTextField.getPassword()).trim().equals("") ? old_password
                : confirmPassword;
        password = password.trim().equals("") ? old_password : password;
        logout = !password.equals(old_password);

        UserValidator uv = new UserValidator();

        if (!uv.validateUsername(username)) {
            ErrorLabel.setText(uv.invalidUsername());
        } else if (!uv.validateUsernameLength(username)) {
            ErrorLabel.setText(uv.invalidUsernameLength());
        } else if (!uv.validateEmail(email)) {
            ErrorLabel.setText(uv.invalidEmail());
        } else if (!uv.validatePassword(password)) {
            ErrorLabel.setText(uv.invalidPassword());
        } else if (!uv.validatePasswordLength(password)) {
            ErrorLabel.setText(uv.invalidPasswordLength());
        } else if (!uv.validateConfirmPassword(password, confirmPassword)) {
            ErrorLabel.setText(uv.invalidConfirmPassword());
        } else if (!uv.validatePhone(phone)) {
            ErrorLabel.setText(uv.invalidPhone());
        } else {
            ErrorLabel.setText("");
            Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
            String[] updatedInfo = { user.getIcno(), username, password, user.getRole(), email, phone, user.getGender(),
                    user.getAddress1(), user.getAddress2(), user.getCity(), user.getZip(), user.getState(),
                    user.getRegistered(), user.getCreditBalance(), user.getApproval() };
            ProfileProcess pp = new ProfileProcess(updatedInfo);

            if (pp.updateProfile(UserDao.loggedIn)) {
                if (!logout) {
                    reset();
                    if (user.getRole().equals(UserRole.CUSTOMER.toString())) {
                        CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
                        cardLayout.show(f.getControlPanel(), "custHomePanel");
                    } else if (user.getRole().equals(UserRole.ADMIN.toString())) {
                        CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
                        cardLayout.show(f.getControlPanel(), "adminHomePanel");
                    } else {
                        CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
                        cardLayout.show(f.getControlPanel(), "adminHomePanel");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Password has been updated, please re-login.");
                    reset();
                    LogoutProcess lp = new LogoutProcess();
                    lp.logout(f);
                }
            } else {
                reset();
                JOptionPane.showMessageDialog(null, "Failed to update profile.");
            }
        }
    }// GEN-LAST:event_SaveChangesButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ResetButtonActionPerformed
         UsernameTextField.setText(old_username);
         EmailTextField.setText(old_email);
         PhoneNOTextField.setText(old_phone);
         ErrorLabel.setText("");
    }// GEN-LAST:event_ResetButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextArea AddressTextArea;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JPasswordField ConfirmPasswordTextField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JTextField GenderTextField;
    private javax.swing.JLabel ICNOLabel;
    private javax.swing.JTextField ICNOTextField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JLabel PhoneNOLabel;
    private javax.swing.JTextField PhoneNOTextField;
    private javax.swing.JLabel ProfileLabel;
    private javax.swing.JLabel RegisteredLabel;
    private javax.swing.JTextField RegisteredTextField;
    private javax.swing.JButton ResetButton;
    private javax.swing.JLabel RoleLabel;
    private javax.swing.JTextField RoleTextField;
    private javax.swing.JButton SaveChangesButton;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}