package UserInterface;

import Classes.State;
import Classes.UserRole;
import Processes.RegisterProcess;
import Validator.UserValidator;
import java.awt.CardLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public final class RegisterPanel extends javax.swing.JPanel {
    public RegisterPanel() {
        initComponents();
        reset();
    }

    public void reset() {
        StateComboBox.setModel(new DefaultComboBoxModel(State.values()));
        UsernameTextField.setText("");
        ICNOTextField.setText("");
        PasswordTextField.setText("");
        ConfirmPasswordTextField.setText("");
        EmailTextField.setText("");
        PhoneNOTextField.setText("");
        GenderButtonGroup.clearSelection();
        AddressLine1TextField.setText("");
        AddressLine2TextField.setText("");
        CityTextField.setText("");
        ZIPCodeTextField.setText("");
        ErrorLabel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderButtonGroup = new javax.swing.ButtonGroup();
        RegistrationLabel = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        ICNOLabel = new javax.swing.JLabel();
        ICNOTextField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordTextField = new javax.swing.JPasswordField();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        ConfirmPasswordTextField = new javax.swing.JPasswordField();
        EmailLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        PhoneNOLabel = new javax.swing.JLabel();
        PhoneNOTextField = new javax.swing.JTextField();
        RegisterButton = new javax.swing.JButton();
        LoginLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        MaleRadioButton = new javax.swing.JRadioButton();
        FemaleRadioButton = new javax.swing.JRadioButton();
        ErrorLabel = new javax.swing.JLabel();
        AddressLine1Label = new javax.swing.JLabel();
        AddressLine1TextField = new javax.swing.JTextField();
        AddressLine2Label = new javax.swing.JLabel();
        AddressLine2TextField = new javax.swing.JTextField();
        CityLabel = new javax.swing.JLabel();
        CityTextField = new javax.swing.JTextField();
        StateLabel = new javax.swing.JLabel();
        StateComboBox = new javax.swing.JComboBox<>();
        ZIPCodeLabel = new javax.swing.JLabel();
        ZIPCodeTextField = new javax.swing.JTextField();

        RegistrationLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        RegistrationLabel.setText("Registration");

        UsernameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UsernameLabel.setText("Username");

        ICNOLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ICNOLabel.setText("NRIC/Passport No.");

        ICNOTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PasswordLabel.setText("Password");
        PasswordLabel.setToolTipText("");

        PasswordTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PasswordTextField.setToolTipText("");

        ConfirmPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ConfirmPasswordLabel.setText("Confirm Password");

        ConfirmPasswordTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmailLabel.setText("Email");

        EmailTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        PhoneNOLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PhoneNOLabel.setText("Phone No.");

        PhoneNOTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        RegisterButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RegisterButton.setText("Register");
        RegisterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        LoginLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LoginLabel.setText("Already have an account");
        LoginLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginLabelMouseClicked(evt);
            }
        });

        GenderLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GenderLabel.setText("Gender");

        GenderButtonGroup.add(MaleRadioButton);
        MaleRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MaleRadioButton.setText("Male");
        MaleRadioButton.setActionCommand("M");

        GenderButtonGroup.add(FemaleRadioButton);
        FemaleRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FemaleRadioButton.setText("Female");
        FemaleRadioButton.setActionCommand("F");

        ErrorLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ErrorLabel.setForeground(new java.awt.Color(255, 51, 51));

        AddressLine1Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AddressLine1Label.setText("Address Line 1");

        AddressLine1TextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        AddressLine2Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AddressLine2Label.setText("Address Line 2");

        AddressLine2TextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CityLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CityLabel.setText("City");

        CityTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        StateLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        StateLabel.setText("State");

        StateComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ZIPCodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ZIPCodeLabel.setText("ZIP/Postal Code");
        ZIPCodeLabel.setToolTipText("");

        ZIPCodeTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(AddressLine1Label)
                                                                        .addComponent(ConfirmPasswordLabel)
                                                                        .addComponent(AddressLine2Label)
                                                                        .addComponent(ZIPCodeLabel))
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(
                                                                                                AddressLine1TextField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                244,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(
                                                                                                ConfirmPasswordTextField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                244,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(
                                                                                                AddressLine2TextField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                244,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                        .addGap(5, 5, 5)
                                                                                        .addComponent(ZIPCodeTextField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                244,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(85, 85, 85)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(PhoneNOLabel)
                                                                        .addComponent(GenderLabel)
                                                                        .addComponent(CityLabel)
                                                                        .addComponent(StateLabel)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(PasswordLabel)
                                                                        .addComponent(UsernameLabel))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(PasswordTextField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        244,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)
                                                                                .addComponent(EmailLabel))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(UsernameTextField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        244,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(ICNOLabel)))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(MaleRadioButton)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(FemaleRadioButton))
                                                        .addComponent(ICNOTextField)
                                                        .addComponent(EmailTextField)
                                                        .addComponent(PhoneNOTextField)
                                                        .addComponent(CityTextField)
                                                        .addComponent(StateComboBox, 0, 240, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(382, 382, 382)
                                                .addComponent(RegistrationLabel))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(200, 200, 200)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ErrorLabel,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 598,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(LoginLabel)
                                                        .addComponent(RegisterButton,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 491,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(78, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(RegistrationLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(UsernameLabel)
                                        .addComponent(ICNOLabel)
                                        .addComponent(ICNOTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(EmailLabel)
                                        .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PasswordLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ConfirmPasswordLabel)
                                        .addComponent(ConfirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PhoneNOTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PhoneNOLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(GenderLabel)
                                        .addComponent(MaleRadioButton)
                                        .addComponent(FemaleRadioButton)
                                        .addComponent(AddressLine1Label)
                                        .addComponent(AddressLine1TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AddressLine2Label)
                                        .addComponent(AddressLine2TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CityLabel)
                                        .addComponent(CityTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(StateLabel)
                                        .addComponent(StateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ZIPCodeLabel)
                                        .addComponent(ZIPCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RegisterButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LoginLabel)
                                .addContainerGap(165, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void LoginLabelMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_LoginLabelMouseClicked
        reset();
        Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
        CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
        cardLayout.show(f.getControlPanel(), "loginPanel");
    }// GEN-LAST:event_LoginLabelMouseClicked

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RegisterButtonActionPerformed
        String username = UsernameTextField.getText();
        String icno = ICNOTextField.getText();
        String password = new String(PasswordTextField.getPassword());
        String confirmPassword = new String(ConfirmPasswordTextField.getPassword());
        String email = EmailTextField.getText();
        String phone = PhoneNOTextField.getText();
        String address1 = AddressLine1TextField.getText();
        String address2 = AddressLine2TextField.getText();
        String city = CityTextField.getText();
        String zip = ZIPCodeTextField.getText();
        String state = StateComboBox.getSelectedItem().toString();

        UserValidator uv = new UserValidator();
        if (!username.trim().equals("") || !icno.trim().equals("") || !password.trim().equals("")
                || !confirmPassword.trim().equals("") || !email.trim().equals("") || !phone.trim().equals("")
                || !address1.trim().equals("") || !city.trim().equals("") || !zip.trim().equals("")) {
            if (GenderButtonGroup.getSelection() != null) {
                ErrorLabel.setText("");
                String gender = GenderButtonGroup.getSelection().getActionCommand();

                if (!uv.validateUsername(username)) {
                    ErrorLabel.setText(uv.invalidUsername());
                } else if (!uv.validateUsernameLength(username)) {
                    ErrorLabel.setText(uv.invalidUsernameLength());
                } else if (!uv.validateICNO(icno)) {
                    ErrorLabel.setText(uv.invalidICNO());
                } else if (!uv.validatePassword(password)) {
                    ErrorLabel.setText(uv.invalidPassword());
                } else if (!uv.validatePasswordLength(password)) {
                    ErrorLabel.setText(uv.invalidPasswordLength());
                } else if (!uv.validateConfirmPassword(password, confirmPassword)) {
                    ErrorLabel.setText(uv.invalidConfirmPassword());
                } else if (!uv.validateEmail(email)) {
                    ErrorLabel.setText(uv.invalidEmail());
                } else if (!uv.validatePhone(phone)) {
                    ErrorLabel.setText(uv.invalidPhone());
                } else if (!uv.validateCity(city)) {
                    ErrorLabel.setText(uv.invalidCity());
                } else if (!uv.validateZIP(zip)) {
                    ErrorLabel.setText(uv.invalidZIP());
                } else {
                    // replace , with : so that it doesn't confused with separator
                    String newAddress1 = address1.replace(",", ":");
                    String newAddress2 = address2.replace(",", ":");

                    RegisterProcess rp = new RegisterProcess(username, icno, password, email, phone, gender,
                            newAddress1, newAddress2, city, zip, state);
                    if (rp.userExisted()) {
                        ErrorLabel.setText(rp.userExistedMessage());
                    } else {
                        ErrorLabel.setText("");
                        if (rp.registerSuccess(UserRole.CUSTOMER.toString(), "NO")) {
                            reset();
                            JOptionPane.showMessageDialog(null,
                                    "Registration complete! Please wait patiently for your account to be approved.");

                            Frame f = (Frame) SwingUtilities.getWindowAncestor(this);
                            CardLayout cardLayout = (CardLayout) f.getControlPanel().getLayout();
                            cardLayout.show(f.getControlPanel(), "loginPanel");
                        }
                    }
                }
            } else {
                ErrorLabel.setText(uv.required());
            }
        } else {
            ErrorLabel.setText(uv.required());
        }
    }// GEN-LAST:event_RegisterButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLine1Label;
    private javax.swing.JTextField AddressLine1TextField;
    private javax.swing.JLabel AddressLine2Label;
    private javax.swing.JTextField AddressLine2TextField;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JTextField CityTextField;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JPasswordField ConfirmPasswordTextField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JRadioButton FemaleRadioButton;
    private javax.swing.ButtonGroup GenderButtonGroup;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel ICNOLabel;
    private javax.swing.JTextField ICNOTextField;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JRadioButton MaleRadioButton;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JLabel PhoneNOLabel;
    private javax.swing.JTextField PhoneNOTextField;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel RegistrationLabel;
    private javax.swing.JComboBox<String> StateComboBox;
    private javax.swing.JLabel StateLabel;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel ZIPCodeLabel;
    private javax.swing.JTextField ZIPCodeTextField;
    // End of variables declaration//GEN-END:variables
}